### ISSUE TITLE
No issue, message

### ISSUE THREAD

**Issue by xyzRGB23** [EldinZenderink/MidiController#2]
i published a repo with wich you can communicate from TouchDesigner to Blender via OSC. With this you could also send Midi events since TouchDesigner can Natively handle Midi input. https://github.com/xyzRGB23/Touch2Blend-OSC

**Comment by EldinZenderink** [comment]
Cool!

Perhaps its usefull  for someone which is familiar with TouchDesigner (I am for one, not). Though I do like the 
enthusiasm, the issues page is not really the right place to promote or share alternatives.

I know there is also another plugin on the market that does more or less the same thing as my plugin, perhaps better in multiple ways. My plugin had as goal to be as simple as possible to use/setup and be as flexible as possible, instead of just "controlling" a fixed property of a single object. Thats where I believe my plugin is different from the others. But to everyone their own!

This is the other much more advanced pluging for if someone else stumbles on this 'issue' and are looking for more advanced/alternatives: http://www.jpfep.net/pages/addroutes/
